### ISSUE TITLE
On Heroku, PostgreSQL I get error on permission MATRIX

### ISSUE THREAD

**Issue by roulendz** [SmarchSoftware/watchtower#17]
Hello, 

So, I am trying out heroku.com and with PostgreSQL I when Syncing roles with premonitions inside Premission Matrix, I got this error.
```
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "AUTO_INCREMENT"
LINE 1: ALTER TABLE permission_role AUTO_INCREMENT = 1
^ (SQL: ALTER TABLE permission_role AUTO_INCREMENT = 1)
```

Do you know where could be problem?

Thanks!

**Comment by landjea** [comment]
Yes, Postgres does not support the Auto_Increment option for tables. You would have to manually change those sources to the equivalent for PostGres. See here for more info : https://www.tutorialspoint.com/postgresql/postgresql_using_autoincrement.htm

**Comment by roulendz** [comment]
Ouh, this is totally out of my skills :)

Thanks!
