### ISSUE TITLE
Placing views in resources

### ISSUE THREAD

**Issue by antoniopaisfernandes** [SmarchSoftware/watchtower#3]
Hi,

I've realized you've placed the views root with  [https://github.com/SmarchSoftware/watchtower/blob/master/src/WatchtowerServiceProvider.php#L32](https://github.com/SmarchSoftware/watchtower/blob/master/src/WatchtowerServiceProvider.php#L32).

Shouldn't they be placed in 'vendor'?
[https://laravel.com/docs/master/packages#views](https://laravel.com/docs/master/packages#views)

**Comment by landjea** [comment]
Hi @antoniopaisfernandes 

It isn't a requirement that they be in the "vendor" folder _(one of the great things about laravel is the freedom)_ and when I was designing watchtower initially I followed a convention from another package that didn't use the vendor folder specifically so I ended up doing the same thing and just placing them in the resources/views folder under "smarch/watchtower".

**Comment by landjea** [comment]
Hi @antoniopaisfernandes 

I hope the explanation was sufficient for your needs. If not, feel free to reopen this and we can continue working on this issue.

Thanks!
