### ISSUE TITLE
Views from bundle used instead of published ones

### ISSUE THREAD

**Issue by ZelimDamian** [SmarchSoftware/watchtower#5]
Changes to the views in ```resources/views/smarch/watchtower``` are not reflected on the website. Changes to the ones in ```vendor/smarch/watchtower``` seem to have effect.

In ```vendor/smarch/watchtower/WatchtowerServiceProvider``` I see:
```php
// load the views
$this->loadViewsFrom(__DIR__.'/Views', 'watchtower');
```

Should it be
```php
$this->loadViewsFrom(base_path('resources/views/smarch/watchtower'), 'watchtower');
```
for the published ones?

Is this what's causing this or am I doing something else wrong?

**Comment by landjea** [comment]
In your watchtower config file, did you set where you want your views to come from?

**Comment by ZelimDamian** [comment]
No changes made to the config. It contains the original view entries as:
``` watchtower::partials.flash ``` etc
I can't seem to find this in docs, could you clarify how this should be changed?

**Comment by landjea** [comment]
Hey there. I didn't really document the config/views stuff as it is a
native function of laravel and not specific to my package. I will check
into what is going on and see what I can find. Thanks!

**Comment by landjea** [comment]
Ugh. Appears it was a misinterpreting of the overiding package views
information. I read the information at
https://laravel.com/docs/5.1/packages#views to read that whatever path I
specified for the views would be the one used. Apparently it doesn't work
that way and ONLY works if the folder is in resources/views/vendor/[name].
I was trying to keep all my views in one "smarch" folder for neatness
sakes. I am going to fix it and push up the fix soon. In the interim, if
you copy the watchtower folder from resources/views/smarch/ to
resources/views/vendor/ you will see your customized views.

Thanks.

**Comment by ZelimDamian** [comment]
Works perfectly. Thank you!

**Comment by landjea** [comment]
No problem. :)
