### ISSUE TITLE
I have installed it by following each step correectly, authentication is working but I am getting full bunch of errors on watchtower page

### ISSUE THREAD

**Issue by rupesh-patel-1** [SmarchSoftware/watchtower#6]
![untitled](https://cloud.githubusercontent.com/assets/343311/14231463/0b044582-f9a2-11e5-9a68-d25ebca2560f.png)

**Comment by landjea** [comment]
It's from line 103 of the master. That's where it shows you your roles. Did you run the migration for roles / permissions? Because that assigns you a default role to help with this.

**Comment by rupesh-patel-1** [comment]
@landjea , I got it solved , I had done migration but I missed the updating User Model while installing sinobi. it did the trick, thanks for the reply.

**Comment by landjea** [comment]
Okay. I will think about adding a "check for roles() method and notify that User model needs updating" step into the watchtower.

Thanks.
