### ISSUE TITLE
 new permissions 

### ISSUE THREAD

**Issue by carneto** [SmarchSoftware/watchtower#7]
Hello i have an dashboard administration menu with the watchtower, localhost:8000/admin/watchtower 
, but also have other menus > http://localhost:8000/store/.
I want to had more permissions outsite de admin/watchtower.

**Comment by landjea** [comment]
Sorry, I don't understand what you are asking.

**Comment by landjea** [comment]
Still not 100% sure what you are requesting but if you are asking can you make permissions for routes that don't include watchtower? Yes. Watchtower is only a front end interface to the [Shinobi](https://github.com/caffeinated/shinobi/wiki/Role-Permissions) permissions system. Please refer to the [Shinobi](https://github.com/caffeinated/shinobi) documentation for permission usage but you can make any permissions you want in watchtower that can be used anywhere in your site.

**Comment by landjea** [comment]
So, for example : if you want a permission to allow "store owners" to be allowed to add new items, you would Create a Role called (for example) "store owners". Then you would create a permission called (for example) "store.add.items". Then you would assign that new permission to your new role. On your "Add Items" page you would check for that permission with "can('store.add.items)" and then code accordingly.

**Comment by carneto** [comment]
thank you for your feedback...

**Comment by landjea** [comment]
No problem. I hope that answers your question.
